### ISSUE TITLE
Magento 2.3.2 invoice not create when payment successful 

### ISSUE THREAD

**Issue by rakeshdonga** [ndp-systemes/magento2-monetico-payment#2]
i have upgrade latest version in magento 2.3.2 but 
when order complete but invoice not generate 
Any help would be appreciated.
Thanks.

**Comment by fronke** [comment]
Hi Rakesh,
I'm also planning to upgrade to 2.3.2 very soon so I'll correct the module in 1-2 week I believe.
With which version of Magento were you using the module before ? 2.3.1 or 2.2.x ?
Have a good day,

**Comment by rakeshdonga** [comment]
Hello @fronke 
ok Thanks for replay
i have upgrade magento 2.2.5 to 2.3.2 version 
Thanks

**Comment by fronke** [comment]
Hi @rakeshdonga ,
I was able to reproduce a bug with Magento 2.3.2 and I guess it was the same that you've found.
It's now fixed and merged on the master branch.
I'll let you test it and close the ticket if the problem has been fixed for you too.
Bye,

**Comment by fronke** [comment]
PS: Dont forget to star/watch the project to be notified for further updates ;)

**Comment by rakeshdonga** [comment]
hello 
@fronke  first thanks for replay and update extension
i have question in old extension one more bug available when payment page redirect and cancel order and not redirect to cart page currently redirect failure page 

i want to redirect to cart page like **paypal**,other payment gateway..
Thanks!!

**Comment by fronke** [comment]
Yeah it's something we have in mind too to improve the module. But right now I don't when we will take the time to do it.
I'll let you know if someday we plan to do it.

**Comment by rakeshdonga** [comment]
Hello @fronke 
In this extension what is use  Monetico **Return Interface URL** ? like below or other? 
Example: 

> https://www.domainname.com/monetico/payment/cgi2confirmation

**Comment by fronke** [comment]
The CGI2 Confirmation URL for the module is https://www.domainname.com/monetico/payment/notify

**Comment by rakeshdonga** [comment]
@fronke 
Thank you For Your Replay
